blank_issues_enabled: true
contact_links:
  - name: Questions and ideas
    url: https://github.com/spherity/business-wallet-requirements/discussions
    about: Use the discussions for open questions and ideas.
