#!/usr/bin/env python3
"""Check the built site (_site): metadata, JSON-LD, figures, robots, sitemap, llms.txt, IndexNow key. Exit 1 on errors."""
import json, os, re, sys, glob
from html.parser import HTMLParser
site = sys.argv[1] if len(sys.argv) > 1 else "_site"
errors, pages = [], []
HREFS = {}
class P(HTMLParser):
    def __init__(s):
        super().__init__(); s._t = False; s._ld = False; s._buf = ""
        s.d = dict(title="", canon=None, desc=None, og=set(), ld=[], imgs=[], h1=0, hrefs=[])
    def handle_starttag(s, t, a):
        a = dict(a)
        if t == "title": s._t = True
        if t == "link" and a.get("rel") == "canonical": s.d["canon"] = a.get("href")
        if t == "meta":
            if a.get("name") == "description": s.d["desc"] = a.get("content")
            if (a.get("property") or "").startswith("og:"): s.d["og"].add(a["property"])
        if t == "script" and a.get("type") == "application/ld+json": s._ld = True; s._buf = ""
        if t == "img": s.d["imgs"].append(a)
        if t == "a" and a.get("href"): s.d["hrefs"].append(a["href"])
        if t == "h1": s.d["h1"] += 1
    def handle_endtag(s, t):
        if t == "title": s._t = False
        if t == "script" and s._ld: s.d["ld"].append(s._buf); s._ld = False
    def handle_data(s, x):
        if s._t: s.d["title"] += x
        if s._ld: s._buf += x
for f in glob.glob(f"{site}/**/*.html", recursive=True):
    rel = os.path.relpath(f, site)
    if rel.startswith("assets") or rel == "404.html": continue
    p = P(); p.feed(open(f, encoding="utf-8").read()); d = p.d; pages.append((rel, d))
    if not d["title"].strip(): errors.append(f"{rel}: no <title>")
    if not d["desc"] or len(d["desc"]) < 50: errors.append(f"{rel}: description missing or too short")
    if not d["canon"]: errors.append(f"{rel}: no canonical")
    for og in ("og:title", "og:description", "og:image", "og:url"):
        if og not in d["og"]: errors.append(f"{rel}: missing {og}")
    if d["h1"] != 1: errors.append(f"{rel}: expected exactly one h1, found {d['h1']}")
    if len(d["ld"]) != 1: errors.append(f"{rel}: expected one JSON-LD block, found {len(d['ld'])}")
    else:
        try:
            j = json.loads(d["ld"][0]); types = []
            for n in j["@graph"]:
                t = n.get("@type"); types += t if isinstance(t, list) else [t]
            for need in ("Organization", "WebSite"):
                if need not in types: errors.append(f"{rel}: JSON-LD lacks {need}")
            if not ({"WebPage", "TechArticle", "CollectionPage", "Article"} & set(types)): errors.append(f"{rel}: JSON-LD lacks a page node")
            ids = [n["@id"] for n in j["@graph"] if "@id" in n]
            if len(ids) != len(set(ids)): errors.append(f"{rel}: duplicate @id in JSON-LD")
            if rel.startswith("figures/") and rel != "figures/index.html" and "ImageObject" not in types: errors.append(f"{rel}: figure page lacks ImageObject")
        except Exception as e: errors.append(f"{rel}: invalid JSON-LD ({e})")
    for im in d["imgs"]:
        if not im.get("alt") and im.get("src", "").startswith(("/", "http", "assets")) and "logo" not in im.get("src", ""): errors.append(f"{rel}: <img> without alt: {im.get('src')}")
base = os.environ.get("BASEURL", "")
def exists(h):
    h = h.split("#")[0].split("?")[0]
    if not h or h.startswith(("http:", "https:", "mailto:", "tel:", "javascript:")): return True
    if base and h.startswith(base): h = h[len(base):]
    if not h.startswith("/"): return True  # relative links are generated by the theme; absolute ones are checked
    cands = [h.lstrip("/"), h.lstrip("/").rstrip("/") + ".html", os.path.join(h.lstrip("/"), "index.html")]
    return any(os.path.exists(os.path.join(site, c)) for c in cands if c) or h == "/"
for rel, d in pages:
    for h in set(d["hrefs"]):
        if not exists(h): errors.append(f"{rel}: broken internal link {h}")
def rd(p): return open(os.path.join(site, p), encoding="utf-8").read() if os.path.exists(os.path.join(site, p)) else None
robots = rd("robots.txt"); sm = rd("sitemap.xml"); llms = rd("llms.txt")
if not robots or "Sitemap:" not in robots: errors.append("robots.txt missing or without Sitemap line")
if not sm: errors.append("sitemap.xml missing")
else:
    locs = re.findall(r"<loc>(.*?)</loc>", sm)
    for rel, _ in pages:
        if rel.startswith("figures/") and rel != "figures/index.html":
            if not any(("/" + rel.replace("index.html", "")) in l for l in locs): errors.append(f"{rel}: not in sitemap")
    if "<image:loc>" not in sm: errors.append("sitemap has no image entries")
    for fig in glob.glob(f"{site}/assets/figures/*.svg"):
        if os.path.basename(fig) not in sm: errors.append(f"{os.path.basename(fig)}: SVG not in sitemap image entries")
if not llms: errors.append("llms.txt missing")
if not glob.glob(f"{site}/[a-f0-9]*.txt") and not os.environ.get("INDEXNOW_KEY"): errors.append("IndexNow key proof file missing")
cfg = open("_config.yml", encoding="utf-8").read() if os.path.exists("_config.yml") else ""
for key in ("imprint_url", "privacy_url"):
    if not re.search(rf"^\s*{key}:\s*\S", cfg, re.M): print(f"WARN {key} is not set in _config.yml (legal pages are a launch blocker)")
# every concept page is in llms.txt, sitemap and linked from the concepts index
idx = rd("concepts/index.html") or ""
for rel, d in pages:
    if rel.startswith("concepts/") and rel != "concepts/index.html":
        slug = rel.replace(".html", "").replace("/index", "")
        name = os.path.basename(slug)
        html = open(os.path.join(site, rel), encoding="utf-8").read()
        thin = 'content="noindex, follow"' in html
        if not thin and llms and f"/concepts/{name}/" not in llms: errors.append(f"{rel}: missing from llms.txt")
        if not thin and sm and f"/concepts/{name}/" not in sm: errors.append(f"{rel}: missing from sitemap.xml")
        if thin and sm and f"/concepts/{name}/" in sm: errors.append(f"{rel}: noindex page must not be in sitemap.xml")
        if f"/concepts/{name}/" not in idx: errors.append(f"{rel}: not linked from the concepts index")
print(f"{len(pages)} pages checked")
if errors: print("\n".join("ERROR " + e for e in errors)); sys.exit(1)
print("OK")
