#!/usr/bin/env python3
"""Derive cross-references from the review proposals into _data/review/cross-references.yml.

  scripts/derive_cross_references.py [CATEGORY ...]     default: AIF

For requirements of a collection category (see `collection: true` in _data/categories.yml) the review proposals
merge-with:<ID> (same obligation elsewhere) and recategorise:<CAT> (fits another category better) are recorded as
cross-references instead of moving or merging the requirement, so the collection stays intact and each entry says where
the obligation is also held. Entries with source: manual are kept. Works for any category.
"""
import os, sys, yaml
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
cats = sys.argv[1:] or ["AIF"]
import difflib, re
R = {}
for f in os.listdir(os.path.join(ROOT, "_requirements")):
    m = yaml.safe_load(re.match(r"---\n(.*?)\n---", open(os.path.join(ROOT, "_requirements", f), encoding="utf-8").read(), re.S).group(1)); R[m["req_id"]] = m
norm = lambda x: re.sub(r"\s+", " ", x).strip().lower()
rv = yaml.safe_load(open(os.path.join(ROOT, "_data/review/requirement-review.yml"), encoding="utf-8"))
p = os.path.join(ROOT, "_data/review/cross-references.yml")
old = yaml.safe_load(open(p, encoding="utf-8")) if os.path.exists(p) else []
keep = [x for x in (old or []) if x.get("source") == "manual" or x["id"].split("-")[1] not in cats]
new = []
for x in rv:
    if x["id"].split("-")[1] not in cats: continue
    v, a = x["verdict"], x.get("verdict_arg")
    if v == "merge-with" and a:
        new.append({"id": x["id"], "relation": "also-covered-by", "targets": [a], "note": "The review found the same obligation or a close variant in the requirement named here.", "source": "review"})
    elif v == "recategorise" and a:
        new.append({"id": x["id"], "relation": "better-fit", "home_category": a, "note": "The review found that this requirement fits category " + a + " better; it stays in the collection.", "source": "review"})
have = {(e["id"], t) for e in new for t in e.get("targets", [])}
for i, m in sorted(R.items()):
    if i.split("-")[1] not in cats: continue
    src = m["sources"][0]
    for j, o in R.items():
        if j == i or j.split("-")[1] in cats and j.split("-")[1] == i.split("-")[1]: continue
        so = o["sources"][0]
        same = so["id"] == src["id"] and norm(so["location"]) == norm(src["location"])
        sim = so["id"] == src["id"] and difflib.SequenceMatcher(None, m["statement"].lower(), o["statement"].lower()).ratio() >= 0.7
        if (same or sim) and (i, j) not in have:
            have.add((i, j)); new.append({"id": i, "relation": "also-covered-by", "targets": [j], "note": "Same source and location, or a near-identical statement, in the requirement named here.", "source": "auto"})
out = sorted(keep + new, key=lambda e: e["id"])
open(p, "w", encoding="utf-8").write("# Cross-references between requirements (generated by scripts/derive_cross_references.py; entries with source: manual are kept).\n# relation: also-covered-by (same or similar obligation held in targets), better-fit (home_category would fit better), profile-of (protocol-specific profile of the neutral requirement in targets).\n" + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=1000))
print(len(new), "derived,", len(keep), "kept, total", len(out))
