#!/usr/bin/env python3
"""Merge reviewer shards (YAML lists) into _data/review/requirement-review.yml and validate them.
Usage: scripts/merge_review.py R1.yml R2.yml ...   Review entries are proposals; requirement files are not changed."""
import os, re, sys, yaml
ROOT = os.path.join(os.path.dirname(__file__), "..")
ids = {f[:-3] for f in os.listdir(os.path.join(ROOT, "_requirements"))}
clusters = {c["code"] for c in yaml.safe_load(open(os.path.join(ROOT, "_data/graph/clusters.yml")))}
cats = {c["code"] for c in yaml.safe_load(open(os.path.join(ROOT, "_data/categories.yml")))}
out, seen, problems = [], set(), []
for p in sys.argv[1:]:
    for e in yaml.safe_load(open(p, encoding="utf-8")):
        rid = e["id"]
        if rid not in ids: problems.append(f"unknown id {rid}"); continue
        if rid in seen: problems.append(f"duplicate {rid}"); continue
        seen.add(rid)
        v = str(e.get("verdict", "ok")); arg = None
        if ":" in v: v, arg = v.split(":", 1)
        if v == "recategorise" and arg not in cats: problems.append(f"{rid}: bad category {arg}"); v, arg = "ok", None
        if v == "merge-with" and arg not in ids: problems.append(f"{rid}: bad merge target {arg}")
        cl = [c for c in e.get("clusters", []) if c in clusters]
        if len(cl) != len(e.get("clusters", [])): problems.append(f"{rid}: unknown cluster in {e.get('clusters')}")
        pr = e.get("priority")
        if pr not in ("P1", "P2", "P3"): problems.append(f"{rid}: bad priority {pr}"); pr = "P3"
        item = {"id": rid, "verdict": v, "priority": pr, "priority_reason": (e.get("priority_reason") or "").strip(), "clusters": cl,
                "applicability": e.get("applicability"), "fidelity": e.get("fidelity"), "verification_ready": e.get("verification_ready")}
        if arg: item["verdict_arg"] = arg
        cs = e.get("corrected_statement")
        if cs: item["corrected_statement"] = cs if isinstance(cs, list) else [str(cs).strip()]
        if e.get("note"): item["note"] = str(e["note"]).strip()
        out.append(item)
missing = sorted(ids - seen)
if missing: problems.append("not reviewed: " + ", ".join(missing))
out.sort(key=lambda x: x["id"])
os.makedirs(os.path.join(ROOT, "_data/review"), exist_ok=True)
header = "# Review proposals for draft requirements (generated by scripts/merge_review.py from reviewer passes on 2026-10-03).\n# These are proposals for the human reviewer; the requirement files are unchanged.\n# verdict: ok | reword | split | merge-with | recategorise | drop. priority: P1 mandatory and architecture-shaping, P2 mandatory but local or standard-derived, P3 peripheral.\n"
open(os.path.join(ROOT, "_data/review/requirement-review.yml"), "w", encoding="utf-8").write(header + yaml.safe_dump(out, sort_keys=False, allow_unicode=True, width=1000))
print(len(out), "entries;", len(problems), "problems")
for x in problems: print(" -", x)
